// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm-1JClCLEBNJDNJ3XzmBX-52NAYfOoso',
    appId: '1:662625647549:web:38520d8668ca99d49230d4',
    messagingSenderId: '662625647549',
    projectId: 'project-app-a9e69',
    authDomain: 'project-app-a9e69.firebaseapp.com',
    storageBucket: 'project-app-a9e69.firebasestorage.app',
    measurementId: 'G-PD6GLW0YP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ7YQpVpCHxXXTvqlOvhnTBFT5t3INJw0',
    appId: '1:662625647549:android:ac79adb9f03d5f6e9230d4',
    messagingSenderId: '662625647549',
    projectId: 'project-app-a9e69',
    storageBucket: 'project-app-a9e69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK2hSJP0Hii6vvEdeZ7Fris4pEug_XV6w',
    appId: '1:662625647549:ios:bc42ce7c75f6a57d9230d4',
    messagingSenderId: '662625647549',
    projectId: 'project-app-a9e69',
    storageBucket: 'project-app-a9e69.firebasestorage.app',
    iosBundleId: 'com.example.quotetowallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK2hSJP0Hii6vvEdeZ7Fris4pEug_XV6w',
    appId: '1:662625647549:ios:bc42ce7c75f6a57d9230d4',
    messagingSenderId: '662625647549',
    projectId: 'project-app-a9e69',
    storageBucket: 'project-app-a9e69.firebasestorage.app',
    iosBundleId: 'com.example.quotetowallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm-1JClCLEBNJDNJ3XzmBX-52NAYfOoso',
    appId: '1:662625647549:web:ad89dff731c1e7bf9230d4',
    messagingSenderId: '662625647549',
    projectId: 'project-app-a9e69',
    authDomain: 'project-app-a9e69.firebaseapp.com',
    storageBucket: 'project-app-a9e69.firebasestorage.app',
    measurementId: 'G-939FDM3W06',
  );
}
